---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-config-merger
  namespace: testgrid-canary
  labels:
    app: testgrid
    channel: stable
    component: config-merger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      channel: stable
      component: config-merger
  template:
    metadata:
      labels:
        app: testgrid
        channel: stable
        component: config-merger
    spec:
      serviceAccountName: config-merger
      containers:
      - name: config-merger
        image: gcr.io/k8s-testgrid/config_merger:v20210928-v0.0.99-11-g719fb26
        args:
        - --config-url=https://raw.githubusercontent.com/kubernetes/test-infra/master/config/mergelists/canary.yaml
        - --confirm
        - --wait=15m
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Uses same as updater
    iam.gke.io/gcp-service-account: testgrid-canary@k8s-testgrid.iam.gserviceaccount.com
  name: config-merger
  namespace: testgrid-canary
