---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: testgrid-config-merger
  namespace: testgrid
  labels:
    app: testgrid
    channel: stable
    component: config-merger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testgrid
      channel: stable
      component: config-merger
  template:
    metadata:
      labels:
        app: testgrid
        channel: stable
        component: config-merger
    spec:
      serviceAccountName: config-merger
      containers:
      - name: config-merger
        image: gcr.io/k8s-testgrid/config_merger:v20211007-v0.0.103-9-gdd19b9e
        args:
        - --config-url=https://raw.githubusercontent.com/kubernetes/test-infra/master/config/mergelists/prod.yaml
        - --confirm
        - --wait=15m
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    # Uses same as updater
    iam.gke.io/gcp-service-account: updater@k8s-testgrid.iam.gserviceaccount.com
  name: config-merger
  namespace: testgrid
